image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""
  AZURE_REGISTRY: $AZURE_REGISTRY
  IMAGE_NAME: $AZURE_REGISTRY/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
  CONTAINER_GROUP: $CONTAINER_GROUP
  CONTAINER_NAME: $CONTAINER_NAME

stages:
  - build
  - push
  - deploy

before_script:
  - apk add --no-cache curl tar openssl sudo bash jq python3 azure-cli
  - az login --service-principal -u $AZURE_APP_ID -p $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
  - az acr login --name $AZURE_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
  only:
    - main

push:
  stage: push
  script:
    - docker push $IMAGE_NAME
  only:
    - main

deploy:
  stage: deploy
  script:
    - az container delete --name $CONTAINER_NAME --resource-group $AZURE_RESOURCE_GROUP --yes
    - az container create --name $CONTAINER_NAME --resource-group $AZURE_RESOURCE_GROUP --image $IMAGE_NAME --registry-login-server $AZURE_REGISTRY --registry-username $AZURE_APP_ID --registry-password $AZURE_PASSWORD --dns-name-label $CONTAINER_NAME-$CI_COMMIT_SHORT_SHA --query "{FQDN:ipAddress.fqdn}" --output tsv
  only:
    - main
